# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-07 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('content', models.TextField()),
                ('photo1', models.ImageField(blank=True, height_field='height_field1', null=True, upload_to='posts/', width_field='width_field1')),
                ('drive_photo1_link', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('height_field1', models.IntegerField(default=0)),
                ('width_field1', models.IntegerField(default=0)),
                ('photo2', models.ImageField(blank=True, height_field='height_field2', null=True, upload_to='posts', width_field='width_field2')),
                ('drive_photo2_link', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('height_field2', models.IntegerField(default=0)),
                ('width_field2', models.IntegerField(default=0)),
                ('photo3', models.ImageField(blank=True, height_field='height_field3', null=True, upload_to='posts', width_field='width_field3')),
                ('drive_photo3_link', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('height_field3', models.IntegerField(default=0)),
                ('width_field3', models.IntegerField(default=0)),
                ('likes', models.PositiveIntegerField(blank=True, default=0)),
                ('comments', models.PositiveIntegerField(blank=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
