# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-07 12:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='profile_photos/', width_field='width_field')),
                ('drive_photo_link', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('activation_code', models.CharField(blank=True, max_length=10, null=True)),
                ('activation_time', models.DateTimeField(auto_now_add=True)),
                ('forgotpass_code', models.CharField(blank=True, max_length=10, null=True)),
                ('recover_code', models.CharField(blank=True, max_length=10, null=True)),
                ('recover_time', models.DateTimeField(blank=True, null=True)),
                ('about_me', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
